### PR TITLE
Increase redis chart dependency

### PR DESCRIPTION
**Pull request by waTeim**
increase to bitnami redis chart 17.1.2; addresses helxplatform/development#940

### CODE REVIEW

**Review by pj-linebaugh — APPROVED** [review]
Would be good to update the docs too.

**Review by YaphetKG — APPROVED** [review]

**Comment by waTeim** [comment]
what's that again, helm doc or something?

**Comment by pj-linebaugh** [comment]
> what's that again, helm doc or something?

helm-docs

**Comment by waTeim** [comment]
fixes #940

**Pull request merged**
